
application:
  viptalk:
#    room-id: "!unRbuLqZDKHPnVEtex:matrix-uat.viptalk.org"
    room-id: "!vFmUBcZRwuyaOApayU:matrix-uat.viptalk.org"
  common:
    depositAmount: 5000000000000
  brand:
    agencyId: 38
    appId: "bc116222"
    token: "58bc2820612d23c34fe43d0b2c6f7223"
    integrations:
      api-gw:
        host: "https://gatquaiznaliz.thaizlapesgw.com"
        path:
          register: "/user/register.aspx"
          register-bot: "/gwms/v1/bot/register.aspx"
          login: "/user/login.aspx"
          update: "/user/update.aspx"
          update-bot: "/gwms/v1/bot/update-fullname.aspx"
          deposit: "/gwms/v1/bot/deposit.aspx"
      game-ms:
        host: "http://gamems.dev:5007"
        path:
          topUp: "/gamems/v1/agency/transfer"
          verifyToken: "/gamems/v1/agency/verifytoken/{token}"
    botConfigPath: "bots/bots-222-prod.yml"
    scheduler:
      balanceCheck: "0 0 0,12 * * *"  # Every day at 00:00 and 12:00
    fileSendDelaySeconds: 10
